version: "2.1"

services:
  db:
    build: ./docker/dockerfiles/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: externals
      MYSQL_PASSWORD: externals
      MYSQL_DATABASE: externals
    volumes:
      - ./data/mysql:/var/lib/mysql

  apachephp:
    build:
      context: ./docker/dockerfiles/apachephp
      args:
        uid: ${CURRENT_UID:-1001}
        gid: "1001"
    volumes:
      - ./:/var/www/html
    links:
      - db

  cliphp:
    build:
      context: ./docker/dockerfiles/apachephp
      args:
        uid: ${CURRENT_UID:-1001}
        gid: "1001"
    user: localUser
    volumes:
        - ./:/var/www/html
    links:
      - db
    command: "false"
