AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'externals.io'

Globals:
    Function:
        Environment:
            Variables:
                APP_ENV: prod
                DB_URL: '{{resolve:ssm:/externals/db_url:1}}'
                ALGOLIA_APP_ID: KSTITII7EC
                ALGOLIA_API_KEY: '{{resolve:ssm:/externals/algolia_api_key:2}}'
#                ALGOLIA_INDEX_PREFIX: v2_ # prod
                ALGOLIA_INDEX_PREFIX: dev_ # staging
#                GITHUB_OAUTH_CLIENT_ID: b75b3226c86d801a95cd # prod
                GITHUB_OAUTH_CLIENT_ID: 422ae3a54f6ebd43895b # staging
                GITHUB_OAUTH_CLIENT_SECRET: '{{resolve:ssm:/externals/github_oauth_client_secret:2}}'
                GITHUB_OAUTH_REDIRECT_URL: 'https://v2.externals.io/login'
                SENTRY_URL: '{{resolve:ssm:/externals/sentry_url:1}}'
                SESSION_SECRET_KEY: '{{resolve:ssm:/externals/session_secret_key:1}}'

Resources:
    Website:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'externals-website'
            Description: 'externals.io website'
            CodeUri: .
            Handler: web/index.php
            Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
            MemorySize: 1024 # The memory size is related to the pricing and CPU power
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:eu-west-1:209497400698:layer:php-73-fpm:3'
            Events:
                # The function will match all HTTP URLs
                HttpRoot:
                    Type: Api
                    Properties:
                        Path: /
                        Method: ANY
                HttpSubPaths:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: ANY
            VpcConfig:
                SecurityGroupIds:
                    - sg-09379891e319fda27
                SubnetIds:
                    - subnet-6dda0d06
                    - subnet-6fda0d04
                    - subnet-6eda0d05
            Policies:
                - AWSLambdaVPCAccessExecutionRole # Allows the lambda to access the VPC

    Console:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'externals-console'
            Description: 'externals.io console'
            CodeUri: .
            Handler: console
            Timeout: 300 # in seconds
            MemorySize: 1024 # The memory size is related to the pricing and CPU power
            Runtime: provided
            Layers:
                # PHP runtime
                - 'arn:aws:lambda:eu-west-1:209497400698:layer:php-73:3'
                # Console layer
                - 'arn:aws:lambda:eu-west-1:209497400698:layer:console:3'
            VpcConfig:
                SecurityGroupIds:
                    - sg-09379891e319fda27
                SubnetIds:
                    - subnet-6dda0d06
                    - subnet-6fda0d04
                    - subnet-6eda0d05
            Policies:
                - AWSLambdaVPCAccessExecutionRole # Allows the lambda to access the VPC

    WebsiteSetup:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: website.yaml
            Parameters:
                ServerlessRestApi: !Ref ServerlessRestApi
                AssetsBucketName: externals-public-assets
                DomainName: v2.externals.io
                CertificateArn: arn:aws:acm:us-east-1:416566615250:certificate/807df63b-c1be-464b-8b8e-a1d3d2d661bb
